### ISSUE TITLE
Error: Cannot create data source "storage": Cannot initialize connector "loopback-component-storage": Cannot find module './client'

### ISSUE THREAD

**Issue by w0w** [strongloop/loopback-component-storage#131]
"version": "1.6.0",

Stack trace
```
Error: Cannot create data source "storage": Cannot initialize connector "loopback-component-storage": Cannot find module './client'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function._load (<appRoot>/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (<appRoot>/node_modules/loopback-component-storage/node_modules/pkgcloud/lib/pkgcloud/amazon/compute/index.js:8:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by richardpringle** [comment]
Hey @w0w, I'll need a little more info than that. How are you trying to use `component-storage`?

**Comment by w0w** [comment]
I checkedin my node_modules folder in git and when cloned my codebase on another machine it throws this error, but running a npm install after removing node_modules fixes the issue.

**Comment by richardpringle** [comment]
@w0w, glad to hear it worked out! In general, it's best practice not to check in your `node_modules` folder. You should update you `package.json` accordingly such that all the proper versions are correct.

Cheers

**Comment by w0w** [comment]
@richardpringle I know not a good practice to check in node_modules but even shrinkwrap is becoming a bit difficult and also we wanted our deployment process to be npm independent hence the checkin. I have seen many people doing that, particularly i was suggested to do exactly same to weed out npm dependency related issue. Just to understand better, do you have any idea on the probable cause of the issue ?

**Comment by richardpringle** [comment]
Not quite sure about what caused the error. As for a suggestion on best practice, I'm sure the answer is out there somewhere. Some modules require compiling so they do need a true install since they will be system dependent.
