### ISSUE TITLE
storage-handler cb is not a funcrion

### ISSUE THREAD

**Issue by Sanbornzhang** [strongloop/loopback-component-storage#149]
# Err message
```
TypeError: cb is not a function
  at ReadStream.<anonymous> (node_modules/loopback-component-storage/lib/storage-handler.js:268:9)
  at emitNone (events.js:72:20)
  at ReadStream.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:921:12)
```
# code
```
    } else {

      var reader = provider.download(params);

      res.type(fileName);

      reader.pipe(res);
      reader.on('error', function(err) {
        handleError(res, err);
      });
      reader.on('end', function() {
        cb();  # cb()is not a function
      });
    }
  }
};
```

**Comment by bendik** [comment]
I got the exact same one. Did you find a fix @Sanbornzhang ?

**Comment by bendik** [comment]
Well, seems like my code passed along an empty object as an options parameter, hence setting the options parameter as the callback and ignoring the actual callback.

**Comment by bendik** [comment]
Wrong again. Wrongly passing down download the req res as parameters was the real cause.
