### ISSUE TITLE
Test failing on Windows node 0.10

### ISSUE THREAD

**Issue by richardpringle** [strongloop/loopback-component-storage#160]
node v4
```shell
$ DEBUG='superagent' mocha test/

  storage service
Thu, 29 Sep 2016 15:18:17 GMT superagent max redirects 5
Thu, 29 Sep 2016 15:18:17 GMT superagent max redirects 0
Thu, 29 Sep 2016 15:18:17 GMT superagent creating `fs.ReadStream` instance for file: C:\Users\IBM_ADMIN\Documents\nodeEE\loopback-component-storage\test\fixtures\app.js
Thu, 29 Sep 2016 15:18:17 GMT superagent set Accept "application/json"
Thu, 29 Sep 2016 15:18:17 GMT superagent post http://localhost:57623/imageContainers/album1/upload
Thu, 29 Sep 2016 15:18:17 GMT superagent setting FormData header: "content-type: multipart/form-data; boundary=--------------------------347644666409256273378526"
Thu, 29 Sep 2016 15:18:17 GMT superagent got FormData Content-Length: 995
Thu, 29 Sep 2016 15:18:17 GMT loopback deprecated Routes "/methods" and "/models" are considered dangerous and should not be used.
Disable them by setting "legacyExplorer=false" in "server/config.json" or via "app.set()". at node_modules\express\lib\router\layer.js:95:5
Thu, 29 Sep 2016 15:18:17 GMT loopback deprecated loopback#context middleware is deprecated. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details. at node_modules\loopback\server\middleware\rest.js:60:32
[Error: contentType "application/javascript" is not allowed (Must be in [image/png, image/jpeg])]
Thu, 29 Sep 2016 15:18:17 GMT superagent post http://localhost:57623/imageContainers/album1/upload -> 500
Thu, 29 Sep 2016 15:18:17 GMT superagent end post http://localhost:57623/imageContainers/album1/upload
Thu, 29 Sep 2016 15:18:17 GMT superagent clear timeout post http://localhost:57623/imageContainers/album1/upload
    √ uploads file wrong content type (91ms)
Thu, 29 Sep 2016 15:18:17 GMT superagent clear timeout post http://localhost:57623/imageContainers/album1/upload

```

node v0.10 (ingoring errors and calling done, **test actually fails**)
```shell
$ DEBUG='superagent' mocha test/


  storage service
Thu, 29 Sep 2016 15:18:45 GMT superagent max redirects 5
Thu, 29 Sep 2016 15:18:45 GMT superagent max redirects 0
Thu, 29 Sep 2016 15:18:45 GMT superagent creating `fs.ReadStream` instance for file: C:\Users\IBM_ADMIN\Documents\nodeEE\loopback-component-storage\test\fixtures\app.js
Thu, 29 Sep 2016 15:18:45 GMT superagent set Accept "application/json"
Thu, 29 Sep 2016 15:18:45 GMT superagent post http://localhost:57630/imageContainers/album1/upload
    √ uploads file wrong content type (79ms)
Thu, 29 Sep 2016 15:18:45 GMT superagent setting FormData header: "content-type: multipart/form-data; boundary=--------------------------679835708150332548229083"
Thu, 29 Sep 2016 15:18:45 GMT superagent got FormData Content-Length: 995
Thu, 29 Sep 2016 15:18:45 GMT loopback deprecated Routes "/methods" and "/models" are considered dangerous and should not be used.
Disable them by setting "legacyExplorer=false" in "server/config.json" or via "app.set()". at node_modules\express\lib\router\layer.js:95:5
Thu, 29 Sep 2016 15:18:45 GMT loopback deprecated loopback#context middleware is deprecated. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details. at node_modules\loopback\server\middleware\rest.js:60:32
[Error: contentType "application/javascript" is not allowed (Must be in [image/png, image/jpeg])]

Thu, 29 Sep 2016 15:18:45 GMT superagent clear timeout post http://localhost:57630/imageContainers/album1/upload

```

**Comment by richardpringle** [comment]
fixed
