### ISSUE TITLE
400 Bad Request on Image Upload - Syntax Error Unexpected Number

### ISSUE THREAD

**Issue by vasumahesh1** [strongloop/loopback-component-storage#78]
Hi tried to upload images after creating a new container via postman got this error:

```
{
    "error": {
        "name": "SyntaxError",
        "status": 400,
        "message": "Unexpected number",
        "body": "------WebKitFormBoundaryRBXQ6k07AaNRNKO4\r\nContent-Disposition: form-data; name=\"file\"; filename=\"test.jpg\"\r\nContent-Type: image/jpeg\r\n\r\n����\u0000\u0010JFIF\u0000\u0001\u0001\u0000\u0000\u0001\u0000\u0001\u0000\u0000��\u0000C\u0000\u0006\u0004\u0005\u0006\u0005\u0004\u0006\u0006\u0005\u0006\u0007\u0007\u0006\b\n\u0010\n\n\t\t\n\u0014\u000e\u000f\f\u0010

//Very Long Content

8��V'�\\Օ�6��NO\u0015���\u0019�p\u0018\u0018\u0019�[���O~jn˲5cԞR��\\u�\u0016���l�ޱ��~5$r��\u0003�-ű�\u001c�9�J$\u0018��φf\u0018��g�!���\r\n------WebKitFormBoundaryA8AXKkhuESNGSNOX--\r\n",
        "statusCode": 400,
        "stack": "SyntaxError: Unexpected number\n    at Object.parse (native)\n    at parse (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback\\node_modules\\body-parser\\lib\\types\\json.js:88:17)\n    at P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback\\node_modules\\body-parser\\lib\\read.js:108:18\n    at done (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback\\node_modules\\body-parser\\node_modules\\raw-body\\index.js:233:14)\n    at IncomingMessage.onEnd (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback\\node_modules\\body-parser\\node_modules\\raw-body\\index.js:279:7)\n    at IncomingMessage.g (events.js:199:16)\n    at IncomingMessage.<anonymous> (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback\\node_modules\\continuation-local-storage\\context.js:74:17)\n    at IncomingMessage.emit (events.js:104:17)\n    at IncomingMessage.emitted [as emit] (P:\\schoolu\\server_workbench\\schoolu\\node_modules\\loopback\\node_modules\\continuation-local-storage\\node_modules\\emitter-listener\\listener.js:122:21)\n    at _stream_readable.js:908:16"
    }
}
```

Any thoughts why it gave 400?

**Comment by julien-sarazin** [comment]
same here, did you find a fix?

**Comment by vasumahesh1** [comment]
I was making a cordova app, so I used ngCordova's FileTransfer

```js
var options = new FileUploadOptions();
options.fileKey = "file"; // To send the File to StrongLoop as "file" attribute
var extension = fileURL.substr(fileURL.lastIndexOf('.') + 1); // Get Extension
options.fileName = uploadContent.id + "." + extension; // Create a new filename
console.log("Uploading File with Name as " + options.fileName); 
if (uploadContent.type == "image") {
	options.mimeType = "image/" + extension; // set Mime
} 

console.log("MIME Type" + options.mimeType);

var ft = new FileTransfer();
ft.upload(fileURL, encodeURI("http://<hostname>/api/v1/Containers/<mycontainer>/upload"), win, fail, options);
```

By setting the correct MimeType I was able to upload via code. If you are using another environment try a similar approach maybe?

In the above code I was uploading an object `uploadContent` which had `id` and `type(image|video|text)` as params. Using the type I had set the mime type for Images

**Comment by julien-sarazin** [comment]
Problem was on my side, a header "Content-Type": application/json sent.

**Comment by richardpringle** [comment]
Hey @vasumahesh1, @julien-sarazin, did you guys get your issues cleared up? If so I would like to close this. If not, I would like to try to help!

Let me know, cheers.

**Comment by julien-sarazin** [comment]
Yes the problem was on my side. Everything is working fine. 
Thanks!
